language: java

#Following https://docs.travis-ci.com/user/languages/java/ we have to run an update for JDK 8
sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
      
jdk:  
  - oraclejdk8

before_install:
  - cp src/main/properties/log4j.properties src/test/resources/log4j.properties
  - mkdir -p "gerbil_data"
  - curl --retry 4 -L -o "gerbil_data/gerbil_data.zip" "https://github.com/AKSW/gerbil/releases/download/v1.2.5/gerbil_data.zip"
  - unzip "gerbil_data/gerbil_data.zip"
  - touch src/main/properties/gerbil_keys.properties
install:
  - mvn clean compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn package -Dmaven.javadoc.skip=true -B
